# Netlify configuration file

[build]
  publish = "dist"
  command = "yarn build"

[[headers]]
  # Define which paths this specific rule will apply to
  for = "/*"
    [headers.values]
      X-Frame-Options = "DENY"
      X-XSS-Protection = "1; mode=block"
      Cache-Control = "public, max-age=0, must-revalidate"
      X-Content-Type-Options = "nosniff"

[[headers]]
  # Cache static assets for a year
  for = "/assets/*"
    [headers.values]
      Cache-Control = "public, max-age=31536000, immutable"

# Optimize redirects and add SPA handling
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 